/**
 * Browser-side encryption helpers — pinned by ADR-0024 §Encryption and
 * §DEK provenance, and consumed by the upload pipeline +
 * Service-Worker decrypt path (`src/sw/decryptHandler.ts`).
 *
 * Contract:
 *   - DEK = 32-byte AES-256-GCM key generated by `crypto.getRandomValues`,
 *     fresh per attachment, single-use (ADR-0024 §DEK provenance).
 *   - `encryptBlob(plaintext, dek)` returns
 *     `nonce(12) || ciphertext || authTag(16)` — the standard
 *     AES-GCM-with-prefixed-nonce convention (ADR-0024 §Encryption).
 *   - `decryptBlob(ciphertext, dek)` round-trips and verifies the auth
 *     tag; any tampering throws.
 *   - `encodeDekMaterial(dek)` / `decodeDekMaterial(b64)` are the
 *     base64 wire-format helpers used by `init` and `download-url`
 *     (api.md §14.2.11). Lossless and length-validated.
 *
 * NOTE — failing-test step (CONTRIBUTING.md § Workflow step 3): the
 * import `@/domain/clientEncryption` does not exist yet. This file
 * pins the module's contract; the implementer iteration adds the
 * module.
 */

import { describe, it, expect } from 'vitest';

const { generateDek, encryptBlob, decryptBlob, encodeDekMaterial, decodeDekMaterial } =
  await import('@/domain/clientEncryption');

const NONCE_BYTES = 12;
const TAG_BYTES = 16;
const DEK_BYTES = 32;

describe('clientEncryption — generateDek', () => {
  it('returns a 32-byte Uint8Array', () => {
    const dek = generateDek();
    expect(dek).toBeInstanceOf(Uint8Array);
    expect(dek.byteLength).toBe(DEK_BYTES);
  });

  it('produces fresh material on each call (CSPRNG provenance — ADR-0024)', () => {
    // The DEK is documented as fresh-per-attachment via
    // `crypto.getRandomValues`. Two consecutive calls returning the
    // same 32 bytes would either prove the implementation is constant
    // (catastrophic) or the universe is over. The looser equality
    // check still catches a fixed-DEK regression without testing the
    // CSPRNG itself.
    const a = generateDek();
    const b = generateDek();
    expect(a).not.toEqual(b);
  });
});

describe('clientEncryption — encryptBlob format (ADR-0024 §Encryption)', () => {
  it('prefixes a 12-byte nonce and appends the 16-byte AES-GCM auth tag', async () => {
    const dek = generateDek();
    const plaintext = new TextEncoder().encode('Hello, e2e world.');
    const ciphertext = await encryptBlob(plaintext, dek);

    expect(ciphertext).toBeInstanceOf(Uint8Array);
    // Total length = nonce(12) + ct(plaintext.length) + tag(16).
    expect(ciphertext.byteLength).toBe(NONCE_BYTES + plaintext.byteLength + TAG_BYTES);
  });

  it('uses a fresh nonce per call so two ciphertexts of the same plaintext differ', async () => {
    const dek = generateDek();
    const plaintext = new TextEncoder().encode('same plaintext');
    const ct1 = await encryptBlob(plaintext, dek);
    const ct2 = await encryptBlob(plaintext, dek);
    // The first 12 bytes (nonce) must differ — nonce reuse with the
    // same DEK is a catastrophic AES-GCM failure.
    const nonce1 = ct1.slice(0, NONCE_BYTES);
    const nonce2 = ct2.slice(0, NONCE_BYTES);
    expect(nonce1).not.toEqual(nonce2);
  });
});

describe('clientEncryption — round-trip', () => {
  it('decryptBlob recovers the original plaintext byte-for-byte', async () => {
    const dek = generateDek();
    const plaintext = new TextEncoder().encode('round-trip me');
    const ciphertext = await encryptBlob(plaintext, dek);
    const recovered = await decryptBlob(ciphertext, dek);

    expect(recovered).toBeInstanceOf(Uint8Array);
    expect(recovered).toEqual(plaintext);
  });

  it('round-trips a binary payload (non-UTF-8 bytes)', async () => {
    // Production blobs include WebP / JPEG / PDF / DOCX bytes — make
    // sure the helpers are byte-clean and don't accidentally route
    // through a UTF-8 conversion.
    const dek = generateDek();
    const plaintext = new Uint8Array([0x00, 0xff, 0x80, 0x7f, 0xc0, 0x01, 0xfe]);
    const ciphertext = await encryptBlob(plaintext, dek);
    const recovered = await decryptBlob(ciphertext, dek);
    expect(recovered).toEqual(plaintext);
  });
});

describe('clientEncryption — tampering rejection (AES-GCM auth tag)', () => {
  it('throws when the nonce prefix has been flipped', async () => {
    const dek = generateDek();
    const plaintext = new TextEncoder().encode('intact');
    const ciphertext = await encryptBlob(plaintext, dek);
    const tampered = ciphertext.slice();
    tampered[0] ^= 0xff;
    await expect(decryptBlob(tampered, dek)).rejects.toThrow();
  });

  it('throws when a byte inside the ciphertext body has been flipped', async () => {
    const dek = generateDek();
    const plaintext = new TextEncoder().encode('intact-body');
    const ciphertext = await encryptBlob(plaintext, dek);
    const tampered = ciphertext.slice();
    // Flip a byte well inside the ct body (past the nonce, before the tag).
    tampered[NONCE_BYTES + 2] ^= 0xff;
    await expect(decryptBlob(tampered, dek)).rejects.toThrow();
  });

  it('throws when a byte in the trailing auth tag has been flipped', async () => {
    const dek = generateDek();
    const plaintext = new TextEncoder().encode('tag-test');
    const ciphertext = await encryptBlob(plaintext, dek);
    const tampered = ciphertext.slice();
    tampered[tampered.byteLength - 1] ^= 0xff;
    await expect(decryptBlob(tampered, dek)).rejects.toThrow();
  });

  it('throws when the wrong DEK is used', async () => {
    const dek = generateDek();
    const wrongDek = generateDek();
    const plaintext = new TextEncoder().encode('right-key-only');
    const ciphertext = await encryptBlob(plaintext, dek);
    await expect(decryptBlob(ciphertext, wrongDek)).rejects.toThrow();
  });
});

describe('clientEncryption — DEK base64 round-trip (api.md §14.2.11 wire format)', () => {
  it('encodeDekMaterial then decodeDekMaterial is the identity', () => {
    const dek = generateDek();
    const b64 = encodeDekMaterial(dek);
    const restored = decodeDekMaterial(b64);
    expect(restored).toEqual(dek);
  });

  it('encodeDekMaterial returns a non-empty base64 string', () => {
    const dek = generateDek();
    const b64 = encodeDekMaterial(dek);
    expect(typeof b64).toBe('string');
    expect(b64.length).toBeGreaterThan(0);
    // 32-byte input encodes to ceil(32/3)*4 = 44 base64 chars.
    expect(b64.length).toBe(44);
  });

  it('decodeDekMaterial rejects input that does not decode to 32 bytes', () => {
    // A short DEK is a structural error — the server's init validation
    // and the SW's decrypt path both rely on the 32-byte invariant
    // (AES-256). Catching the malformed case at the decoder keeps the
    // error close to its source.
    const shortB64 = encodeDekMaterial(new Uint8Array(16));
    expect(() => decodeDekMaterial(shortB64)).toThrow();
  });

  it('decodeDekMaterial rejects an oversized input (>32 bytes)', () => {
    const longB64 = encodeDekMaterial(new Uint8Array(64));
    expect(() => decodeDekMaterial(longB64)).toThrow();
  });
});
