/**
 * Shared init-payload fixtures for attachment route + service tests.
 *
 * Under ADR-0024 (per-attachment envelope encryption) the init payload
 * carries:
 *   - plaintext metadata: `fileName`, `mimeType`, `sizeBytes` (server-
 *     side row state — drive the per-file cap, MIME whitelist, and
 *     download Content-Disposition; never sent on the wire to storage),
 *   - per-blob `dekMaterial` (base64 of the 32-byte AES-256-GCM DEK
 *     generated by the browser via `crypto.getRandomValues`),
 *   - per-blob `ciphertextSizeBytes` + `ciphertextContentMd5` — the
 *     server signs both into the presigned PUT (Content-Length +
 *     Content-MD5).
 *
 * For photo init bodies (`hasThumbnail = true`) the analogous thumbnail
 * triplet (`thumbDekMaterial`, `ciphertextThumbSizeBytes`,
 * `ciphertextThumbContentMd5`) lands too — thumbnails are independent
 * ciphertext objects with their own DEKs (api.md §14.2.11).
 *
 * `STUB_MD5_BASE64` (MD5 of the empty string) is the placeholder for
 * the ciphertext MD5 in tests that exercise the route/service layer in
 * isolation — the server-side route doesn't recompute the hash, only
 * signs the value into the PUT URL. Tests that exercise upload-time
 * integrity (round-trip MD5 verification at storage) supply the actual
 * MD5 of the ciphertext bytes.
 */

import { Buffer } from 'node:buffer';

/** MD5 of the empty string, RFC 1864 base64. Schema-valid placeholder. */
export const STUB_MD5_BASE64 = '1B2M2Y8AsgTpgAmY7PhCfg==';

/**
 * Stable test-default DEK material — 32 bytes of `0x42`, base64-encoded.
 * Routes don't care about the actual key value for non-decrypt tests;
 * pinning a constant keeps fixtures deterministic.
 */
export const STUB_DEK_MATERIAL = Buffer.alloc(32, 0x42).toString('base64');

/** Symmetric default for the thumbnail DEK. Distinct constant so a
 * regression that confused original-vs-thumbnail keys is detectable. */
export const STUB_THUMB_DEK_MATERIAL = Buffer.alloc(32, 0x43).toString('base64');

export interface InitOverrides {
  fileName?: string;
  mimeType?: string;
  /** Plaintext byte count — drives per-file cap + export envelope. */
  sizeBytes?: number;
  label?: string;
  hasThumbnail?: boolean;
  /** Base64 of the 32-byte AES-256-GCM DEK for the original blob. */
  dekMaterial?: string;
  /** Ciphertext byte count — what the server signs as Content-Length. */
  ciphertextSizeBytes?: number;
  /** RFC 1864 base64 MD5 of the ciphertext bytes. */
  ciphertextContentMd5?: string;
  /** Base64 of the 32-byte DEK for the thumbnail blob (photos only). */
  thumbDekMaterial?: string;
  /** Ciphertext byte count for the thumbnail (photos only). */
  ciphertextThumbSizeBytes?: number;
  /** RFC 1864 base64 MD5 of the thumbnail ciphertext bytes (photos only). */
  ciphertextThumbContentMd5?: string;
  /**
   * Pre-e2e plaintext thumbnail byte count. Retained as an accepted
   * override key so legacy callers in `attachments-thumb-size.test.ts`
   * still typecheck; the body builders intentionally do NOT forward it
   * — the route's e2e contract has no plaintext-thumb-size field.
   * Those tests need their own e2e migration in a separate task.
   */
  thumbSizeBytes?: number;
  /**
   * Pre-e2e plaintext-MD5 field, retained for the same reason as
   * `thumbSizeBytes` above — typecheck compatibility for legacy tests
   * that reference it.
   */
  contentMd5?: string;
}

/**
 * Build a photo init payload (image MIME, `foto` label, thumbnail by
 * default). Override any field via `overrides`.
 */
export function photoInitBody(overrides: InitOverrides = {}): Record<string, unknown> {
  const hasThumbnail = overrides.hasThumbnail ?? true;
  return {
    fileName: overrides.fileName ?? 'photo.jpg',
    mimeType: overrides.mimeType ?? 'image/jpeg',
    sizeBytes: overrides.sizeBytes ?? 120_000,
    label: overrides.label ?? 'foto',
    hasThumbnail,
    dekMaterial: overrides.dekMaterial ?? STUB_DEK_MATERIAL,
    ciphertextSizeBytes: overrides.ciphertextSizeBytes ?? 120_064,
    ciphertextContentMd5: overrides.ciphertextContentMd5 ?? STUB_MD5_BASE64,
    ...(hasThumbnail
      ? {
          thumbDekMaterial: overrides.thumbDekMaterial ?? STUB_THUMB_DEK_MATERIAL,
          ciphertextThumbSizeBytes: overrides.ciphertextThumbSizeBytes ?? 8_064,
          ciphertextThumbContentMd5: overrides.ciphertextThumbContentMd5 ?? STUB_MD5_BASE64,
        }
      : {}),
  };
}

/**
 * Build a binary init payload (PDF, `rechnung` label, no thumbnail by
 * default). Override any field via `overrides`.
 */
export function binaryInitBody(overrides: InitOverrides = {}): Record<string, unknown> {
  return {
    fileName: overrides.fileName ?? 'doc.pdf',
    mimeType: overrides.mimeType ?? 'application/pdf',
    sizeBytes: overrides.sizeBytes ?? 50_000,
    label: overrides.label ?? 'rechnung',
    hasThumbnail: overrides.hasThumbnail ?? false,
    dekMaterial: overrides.dekMaterial ?? STUB_DEK_MATERIAL,
    ciphertextSizeBytes: overrides.ciphertextSizeBytes ?? 50_064,
    ciphertextContentMd5: overrides.ciphertextContentMd5 ?? STUB_MD5_BASE64,
  };
}
