#!/usr/bin/env bash
#
# VPS side of scripts/sync-dev-to-vps.sh. Not intended to be run directly.
# The orchestrator streams this script over SSH (`ssh hetzner bash -s`) with
# these env vars already transferred plus a $REMOTE_TMP directory on the VPS
# containing db.sql and bucket/ prepared by the orchestrator.
#
# Env contract:
#   REMOTE_TMP       directory on VPS holding db.sql and bucket/
#   MC_IMAGE         minio/mc image tag
#   COMPOSE_PROJECT  compose project name (projekt-manager) — used to find
#                    the running containers. The bucket itself lives at
#                    Backblaze B2 since the ddff944 topology switch (ADR-0022);
#                    this script reads B2 credentials, endpoint, and bucket
#                    name from the running app container's env.
#
# Exit codes:
#   0  success
#   1  restore failed (app is restarted if it was running)
#
# The trap always starts the app container back on exit, even on failure, to
# avoid leaving the VPS with a stopped app after a partial sync.

set -euo pipefail

: "${REMOTE_TMP:?REMOTE_TMP must be set}"
: "${MC_IMAGE:?MC_IMAGE must be set}"
: "${COMPOSE_PROJECT:?COMPOSE_PROJECT must be set}"

DB_CONTAINER="${COMPOSE_PROJECT}-db-1"
APP_CONTAINER="${COMPOSE_PROJECT}-app-1"
BACKUP_CONTAINER="${COMPOSE_PROJECT}-backup-1"

# Restart whatever we stopped, even on failure. Without this a failed restore
# leaves the app down and the operator has to manually `docker start` it.
was_app_running=0
was_backup_running=0
restart_stopped() {
  rc=$?
  if [ "$was_app_running" = "1" ]; then
    docker start "$APP_CONTAINER" >/dev/null 2>&1 || true
  fi
  if [ "$was_backup_running" = "1" ]; then
    docker start "$BACKUP_CONTAINER" >/dev/null 2>&1 || true
  fi
  exit "$rc"
}
trap restart_stopped EXIT

running() {
  docker ps --format '{{.Names}}' | grep -qx "$1"
}

# Read B2 credentials, endpoint, and bucket name from the running app
# container's env BEFORE we stop it — once stopped, `docker exec printenv`
# returns nothing. The container is the authoritative source for the live
# config (compose interpolates from .env + secrets.env.age into its
# `environment:` block at startup), so we avoid re-parsing those files and
# don't need to prompt for the secrets.env.age passphrase here.
B2_ENDPOINT=$(docker exec "$APP_CONTAINER" printenv STORAGE_ENDPOINT)
B2_BUCKET=$(docker exec "$APP_CONTAINER" printenv STORAGE_BUCKET)
B2_KEY=$(docker exec "$APP_CONTAINER" printenv STORAGE_ACCESS_KEY)
B2_SECRET=$(docker exec "$APP_CONTAINER" printenv STORAGE_SECRET_KEY)

# Stop the app (and backup if active) so psql can drop+recreate tables
# without fighting open connections. backup is profile-gated so it may not
# exist.
if running "$APP_CONTAINER"; then
  echo "  stopping app..."
  docker stop "$APP_CONTAINER" >/dev/null
  was_app_running=1
fi
if running "$BACKUP_CONTAINER"; then
  echo "  stopping backup..."
  docker stop "$BACKUP_CONTAINER" >/dev/null
  was_backup_running=1
fi

# Restore DB. Using `psql` (not pg_restore) because the dump is plain SQL;
# the orchestrator chose plain format for readability and because the dump
# contains DROP TABLE IF EXISTS statements generated by `pg_dump --clean
# --if-exists`, which psql applies before recreating. ON_ERROR_STOP=1 aborts
# on the first failure instead of leaving the DB in a half-restored state.
echo "  restoring database..."
docker exec -i "$DB_CONTAINER" \
  psql -U pm -d projekt_manager -v ON_ERROR_STOP=1 --quiet \
  < "$REMOTE_TMP/db.sql" >/dev/null

# Mirror local-dump → B2 bucket. `mc alias set` avoids URL-encoding
# pitfalls of `MC_HOST_*=` when an applicationKey contains `+` or `/`.
# `--overwrite` replaces objects whose keys match (creating a new B2
# version, never destroying the previous one); `--remove` drops keys at the
# destination that are absent in the source (issuing a version-less
# DeleteObject, which on B2 creates a delete marker — safe under ADR-0022's
# capability split: the app key has writeFiles but not deleteFiles, so no
# version is destroyed). Together they make the VPS bucket an exact mirror
# of the local dump, with no destructive writes.
#
# `--md5` is required: the bucket has Compliance Object Lock with a
# bucket-default retention (ADR-0022), so every PutObject implicitly carries
# Object Lock parameters. The S3 spec requires PutObject with Object Lock
# parameters to include Content-MD5 or x-amz-checksum-* — B2 enforces this
# and rejects bare PUTs with "Content-MD5 OR x-amz-checksum-* HTTP header
# is required for Put Object requests with Object Lock parameters". Trades
# one extra read pass per file for compliance with the lock contract.
echo "  restoring object storage..."
docker run --rm \
  -v "$REMOTE_TMP/bucket:/data:ro" \
  -e B2_ENDPOINT="$B2_ENDPOINT" \
  -e B2_KEY="$B2_KEY" \
  -e B2_SECRET="$B2_SECRET" \
  -e B2_BUCKET="$B2_BUCKET" \
  --entrypoint sh \
  "$MC_IMAGE" \
  -c '
    mc alias set b2 "$B2_ENDPOINT" "$B2_KEY" "$B2_SECRET" --api S3v4 >/dev/null
    mc mirror --overwrite --remove --md5 /data "b2/$B2_BUCKET"
  ' >/dev/null

# Start app back. Clear the trap flag first so the trap doesn't double-start
# after a successful restart.
echo "  starting app..."
docker start "$APP_CONTAINER" >/dev/null
was_app_running=0
if [ "$was_backup_running" = "1" ]; then
  docker start "$BACKUP_CONTAINER" >/dev/null
  was_backup_running=0
fi

# Poll /api/health via node fetch inside the app container — same probe the
# deploy script uses. Bypasses Caddy and TLS so a failure here isolates to
# the app + db + storage triad.
echo "  waiting for health..."
timeout=60
elapsed=0
until docker exec "$APP_CONTAINER" node -e \
  "fetch('http://localhost:3000/api/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))" \
  2>/dev/null; do
  sleep 2
  elapsed=$((elapsed + 2))
  if [ "$elapsed" -ge "$timeout" ]; then
    echo "  ERROR: health check failed after ${timeout}s" >&2
    docker logs --tail=40 "$APP_CONTAINER" >&2
    exit 1
  fi
done

echo "  healthy"
trap - EXIT
