#!/usr/bin/env bash
#
# VPS side of scripts/sync-dev-to-vps.sh. Not intended to be run directly.
# The orchestrator streams this script over SSH (`ssh hetzner bash -s`) with
# these env vars already transferred plus a $REMOTE_TMP directory on the VPS
# containing db.sql and bucket/ prepared by the orchestrator.
#
# Env contract:
#   REMOTE_TMP       directory on VPS holding db.sql and bucket/
#   MC_IMAGE         minio/mc image tag (must match the one the app stack uses)
#   BUCKET           MinIO bucket name (projekt-manager)
#   COMPOSE_PROJECT  compose project name (projekt-manager) — used for network
#
# Exit codes:
#   0  success
#   1  restore failed (app is restarted if it was running)
#
# The orchestrator always starts the app container back on exit, even on
# failure, to avoid leaving the VPS with a stopped app after a partial sync.

set -euo pipefail

: "${REMOTE_TMP:?REMOTE_TMP must be set}"
: "${MC_IMAGE:?MC_IMAGE must be set}"
: "${BUCKET:?BUCKET must be set}"
: "${COMPOSE_PROJECT:?COMPOSE_PROJECT must be set}"

DB_CONTAINER="${COMPOSE_PROJECT}-db-1"
STORAGE_CONTAINER="${COMPOSE_PROJECT}-storage-1"
APP_CONTAINER="${COMPOSE_PROJECT}-app-1"
BACKUP_CONTAINER="${COMPOSE_PROJECT}-backup-1"
NETWORK="${COMPOSE_PROJECT}_default"

# Restart whatever we stopped, even on failure. Without this a failed restore
# leaves the app down and the operator has to manually `docker start` it.
was_app_running=0
was_backup_running=0
restart_stopped() {
  rc=$?
  if [ "$was_app_running" = "1" ]; then
    docker start "$APP_CONTAINER" >/dev/null 2>&1 || true
  fi
  if [ "$was_backup_running" = "1" ]; then
    docker start "$BACKUP_CONTAINER" >/dev/null 2>&1 || true
  fi
  exit "$rc"
}
trap restart_stopped EXIT

running() {
  docker ps --format '{{.Names}}' | grep -qx "$1"
}

# Stop the app (and backup if active) so psql can drop+recreate tables without
# fighting open connections. backup is profile-gated so it may not exist.
if running "$APP_CONTAINER"; then
  echo "  stopping app..."
  docker stop "$APP_CONTAINER" >/dev/null
  was_app_running=1
fi
if running "$BACKUP_CONTAINER"; then
  echo "  stopping backup..."
  docker stop "$BACKUP_CONTAINER" >/dev/null
  was_backup_running=1
fi

# Restore DB. Using `psql` (not pg_restore) because the dump is plain SQL; the
# orchestrator chose plain format for readability and because the dump contains
# DROP TABLE IF EXISTS statements generated by `pg_dump --clean --if-exists`,
# which psql applies before recreating. ON_ERROR_STOP=1 aborts on the first
# failure instead of leaving the DB in a half-restored state.
echo "  restoring database..."
docker exec -i "$DB_CONTAINER" \
  psql -U pm -d projekt_manager -v ON_ERROR_STOP=1 --quiet \
  < "$REMOTE_TMP/db.sql" >/dev/null

# Pull the VPS MinIO credentials from the running storage container's env so we
# don't need to decrypt secrets.env.age for a sync. The orchestrator does the
# same for the local side.
VPS_MINIO_USER=$(docker exec "$STORAGE_CONTAINER" printenv MINIO_ROOT_USER)
VPS_MINIO_PASS=$(docker exec "$STORAGE_CONTAINER" printenv MINIO_ROOT_PASSWORD)

# Mirror bucket. `--overwrite` replaces objects with matching keys; `--remove`
# deletes objects on the VPS that are absent locally. Together they make the
# VPS bucket an exact copy of the local bucket.
echo "  restoring object storage..."
docker run --rm \
  --network "$NETWORK" \
  -v "$REMOTE_TMP/bucket:/data:ro" \
  -e MC_HOST_dst="http://${VPS_MINIO_USER}:${VPS_MINIO_PASS}@storage:9000" \
  "$MC_IMAGE" \
  mirror --overwrite --remove /data "dst/$BUCKET" >/dev/null

# Start app back. Clear the trap flag first so the trap doesn't double-start
# after a successful restart.
echo "  starting app..."
docker start "$APP_CONTAINER" >/dev/null
was_app_running=0
if [ "$was_backup_running" = "1" ]; then
  docker start "$BACKUP_CONTAINER" >/dev/null
  was_backup_running=0
fi

# Poll /api/health via node fetch inside the app container — same probe the
# deploy script uses. Bypasses Caddy and TLS so a failure here isolates to the
# app + db + storage triad.
echo "  waiting for health..."
timeout=60
elapsed=0
until docker exec "$APP_CONTAINER" node -e \
  "fetch('http://localhost:3000/api/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))" \
  2>/dev/null; do
  sleep 2
  elapsed=$((elapsed + 2))
  if [ "$elapsed" -ge "$timeout" ]; then
    echo "  ERROR: health check failed after ${timeout}s" >&2
    docker logs --tail=40 "$APP_CONTAINER" >&2
    exit 1
  fi
done

echo "  healthy"
trap - EXIT
